### ISSUE TITLE
Module 8 typo and broken link

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/EUeLearning#1]
Hi @davetaz 
Firstly, thanks for the great resource I found at http://www.europeandataportal.eu/elearning/en/
I hope this is the right place to report issues.

"Geting to grips with platforms" is mis-spelt; it should be "Getting".

Also the link to https://how-to.usopendata.org/basics/data-repositories.html in Open data platform design approaches, returns an error.

**Comment by davetaz** [comment]
Thanks @Stephen-Gates for contributing this issue! 

This repo is the web hosting for the EU version of the eLearning. The master repo is at https://github.com/theodi/ODI-eLearning and this has branches for all modules and tags etc. 

I can easily copy the issue over but I thought it might be nice for you to (if you want). This way you can follow the issue to closure which will we likely do next week.

I'll put a note in the README on this repo for where the master is.

**Comment by Stephen-Gates** [comment]
@davetaz - Issue copied over.
